Feed sorting
spaceshelter/orbitar pull request #139
Opened 2022-09-04 02:22 UTC by pazoozoo42

As discussed, this is changed to return feed sorting in the feed payload
[initial PR](https://github.com/spaceshelter/orbitar/pull/123) for the reference

2022-09-04 22:28 UTC, Aivean commented on backend/src/api/SiteController.ts
> +            site: joiSite.required(),
Can reuse `joiSite` validator for `site` field in the other API methods (above).

2022-09-04 22:44 UTC, Aivean commented on backend/src/managers/FeedManager.ts
>          // check if fanned out
Need to add another flag, `subscriptions:${forUserId}:created_at:fanned` that corresponds to the completion of the fanning out of the new redis feed cache. The key that corresponds to the requested `sorting` method should be checked, and if it's not present, `await this.pullSubscriptionsFeed(forUserId);` should be called.

2022-09-04 22:53 UTC, Aivean commented on frontend/src/Pages/FeedPage.tsx
> +    const [changeSorting, setChangeSorting] = useState(-1);
Nit: seems that `-1` doesn't have any special connotation here, probably better to replace it with `undefined`.

2022-09-04 22:59 UTC, Aivean commented on frontend/src/Pages/FeedPage.tsx
> +        const feedSorting = (e.currentTarget as HTMLAnchorElement).dataset.feedSorting;
Is there a reason to read DOM attributes here? Seems like an easier way would be to pass the sorting value as a parameter to the function:

```
const handleFeedSortingChange = (value: FeedSorting) => async (e: React.MouseEvent) => {
 ...
}

<a href='#' className={sorting === FeedSorting.postCommentedAt ? styles.active : ''} onClick={handleFeedSortingChange(FeedSorting.postCommentedAt)}>LIVE</a>
```

2022-09-04 23:02 UTC, Aivean requested changes
Overall, looks good.

However, currently the feed with the new sorting method will be empty for existing users (that have their feed already materialized). Need to address that.

2022-09-04 23:58 UTC, Aivean approved these changes
I fixed my own nits and tested it locally.

@ArtCraft, please check it locally as well, but I think it's ready to be merged.

2022-09-05 13:19 UTC, pazoozoo42 commented
@Aivean thank you, appreciate your help

2022-09-15 02:23 UTC, Aivean approved these changes
Reviewed and checked locally.

Btw, we can make this loading progress bar global (add it to mobx appState) and reuse it in other places.

2022-09-20 02:04 UTC, merged