Add basic update notification mechanism
spaceshelter/orbitar pull request #326
Opened 2023-05-26 21:50 UTC by Aivean

2023-05-27 02:09 UTC, Aivean commented
@Lexy2 has a good point, it makes sense to reload the page transparently to the user (e.g. on certain navigation events). Marking as draft for now.

2023-05-27 11:17 UTC, Lexy2 requested changes
Let's add the FINGERPRINT param, even blank, to the .env.sample and rename gitHash class to Fingerprint

2023-05-27 11:17 UTC, Lexy2 commented on frontend/src/AppState/AppState.tsx
> +class GitHash {
Could we rename this class to fingerprint to maintain consistency, readability and support?

2023-05-27 11:17 UTC, Lexy2 commented on docker-compose.dev.yml
> +      FINGERPRINT: ${FINGERPRINT}
Could we also add the new `FINGERPRINT=` line to `.env.sample`, please?

2023-05-27 11:22 UTC, Lexy2 commented
Testing changed fingerprint:
1. Add `FINGERPRINT=xxx` to your `.env` file
2. Load the pages, click links, observe that the pages do not reload. Keep the page open.
3. Check that the returned header from API calls is `X-Fingerprint: xxx`
4. Change the fingerprint value in the `.env` file to `FINGERPRINT=yyy`
5. Stop Caddy: `docker stop orbitar-caddy-1`
6. Kill Caddy: `docker rm orbitar-caddy-1`
7. Run `docker-compose -f docker-compose.dev.yml up caddy` to reload
8. Click any link on the orbitar page.
9. Observe that the page is reloaded.

2023-05-27 11:24 UTC, Lexy2 commented
Otherwise looks good, I like the new update mechanism way more than an explicit _Reload_ button.

2023-05-27 16:53 UTC, Aivean commented
> Otherwise looks good, I like the new update mechanism way more than an explicit _Reload_ button.

I thought more about it, there is a chance to simplify its implementation. Will try today.

2023-05-28 03:20 UTC, Aivean commented
@Lexy2 , I simplified the reloading logic (add addressed your comment), please check.

2023-05-28 22:52 UTC, Lexy2 approved these changes

2023-05-28 22:52 UTC, merged

2023-05-28 22:53 UTC, Lexy2 commented
If someone has a page open and a server update is deployed, then when this person clicks a link to open a post, for example, the link will open and then the page will reload.
Which is not nice, but much better than attaching an observable to each link tag.